import "./globals.css";
import { Montserrat } from "next/font/google";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const montserratFont = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

export const metadata = {
  title: "BurkitAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserratFont.variable} antialiased`}>
        <SidebarProvider>
          <AppSidebar />
          <main className="mx-auto relative">
            <SidebarTrigger className="hidden" />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
